# Generated by Django 2.2.5 on 2019-12-14 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NurseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse_day', models.DateTimeField(default=django.utils.timezone.now)),
                ('urine_time', models.CharField(max_length=5, null=True)),
                ('urine_volume', models.PositiveIntegerField(null=True)),
                ('memo', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
