# Generated by Django 2.2.5 on 2019-12-15 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emikoKanri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurserecord',
            name='nurse_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
