# Generated by Django 2.2.5 on 2020-04-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emikoKanri', '0003_auto_20191215_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurserecord',
            name='memo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
